name: crypto_demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0-271.7.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # ui
  fl_chart: ^0.55.1
  font_awesome_flutter: ^10.1.0
  intl: ^0.17.0
  flutter_svg: ^1.1.4
  lottie: ^1.4.2

  # api
  http: ^0.13.5

  # state management
  provider: ^6.0.3

  # caching
  hive: ^2.2.3
  path_provider: ^2.0.11
  cached_network_image: ^3.2.1
  flutter_advanced_networkimage_2: ^2.0.0

  #utils
  connectivity_plus: ^2.3.6+1
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0

  # flutter/hive testing and mocking
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0

  # code generators
  hive_generator: ^1.1.3
  #flutter packages pub run build_runner build
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/

  fonts:
    - family: Onest
      fonts:
        - asset: assets/fonts/Onest-Medium.ttf
          weight: 400
        - asset: assets/fonts/Onest-Bold.ttf
          weight: 700
